### ISSUE TITLE
rpmlint: Bogus dates in changelog

### ISSUE THREAD

**Issue by aron-silverton** [Mellanox/mstflint#10]
$ rpmlint mstflint.spec

mstflint.spec: E: specfile-error warning: bogus date in %changelog: Mon Jan 10 2017 Adham Masarwah <adham at dev.mellanox.co.il>
mstflint.spec: E: specfile-error warning: bogus date in %changelog: Wed May 17 2016 Adrian Chiris <adrianc at dev.mellanox.co.il>
mstflint.spec: E: specfile-error warning: bogus date in %changelog: Wed Jun 05 2015 Adrian Chiris <adrianc at dev.mellanox.co.il>
mstflint.spec: E: specfile-error warning: bogus date in %changelog: Mon Oct 12 2014 Oren Kladnitsky <orenk at dev.mellanox.co.il>
mstflint.spec: E: specfile-error warning: bogus date in %changelog: Mon Jul 31 2014 Oren Kladnitsky <orenk at dev.mellanox.co.il>
mstflint.spec: E: specfile-error warning: bogus date in %changelog: Fri Dec 23 2007 Oren Kladnitsky <orenk at dev.mellanox.co.il>
0 packages and 1 specfiles checked; 6 errors, 0 warnings.

**Comment by adham-mellanox** [comment]
Fixed in master_devel branch, will be merged in master soon
