### ISSUE TITLE
Build instructions are incorrect

### ISSUE THREAD

**Issue by aron-silverton** [Mellanox/mstflint#11]
The build instructions are:

> 3) Installation
>     a) Build the mstflint utility. This package is built using a standard
>        autotools method.
> 	   
>        Example: 
>        > ./configure
>        > make
>        > make install
> 
>        - Run "configure --help" for custom configuration options.
>        - Typically, root privileges are required to run "make install"

However, "configure" is not provided and it appears that running autogen.sh first is required.

**Comment by adham-mellanox** [comment]
These instructions were intended to the released tarball and not for the GIT itself.
Will be updated soon.
