### ISSUE TITLE
Question about 4.12 user manual supported devices 

### ISSUE THREAD

**Issue by bsnapko** [Mellanox/mstflint#162]
The document mstflint_User_Manual_v4_12_0.pdf

In section 1.5 "Supported Mellanox ICs "
The ConnectX-6 and Quantum are listed in the 5th generation of devices. 

In section 2.2 "Access to Hardware Devices" 
The ConnectX-6 and Quantum devices are not listed in the table of devices that mstflint can access. 

I am not sure if the two sections should be an echo of each other, but should section 2.2 include the ConnectX-6 and Quantum devices in the table and the supported access methods? 

Thank you for your help.

**Comment by tomer540** [comment]
Closed due to time limit, if still require addressing – please open a new ticket.
