### ISSUE TITLE
mstflint user tools and kernel module versions are inconsistent

### ISSUE THREAD

**Issue by aron-silverton** [Mellanox/mstflint#178]
Prior mstflint releases bumped the version of kernel-mstflint to match that of the userspace tools even if the kernel module code was unchanged.

The versions are currently out-of-sync. For now, they should probably be kept in-sync. However, in the long term, some better mechanism for maintaining the user tools and the kernel module and their ABI compatibility should be explored.

**Comment by tomer540** [comment]
Closed due to time limit, if still require addressing – please open a new ticket.
