### ISSUE TITLE
Can't compile mstflint-4.9 with gcc-8

### ISSUE THREAD

**Issue by HonggangLI** [Mellanox/mstflint#18]
Failed to compile mstflint-4.9 with Fedora-28 or Fedora-Rawhide (F29). gcc-8 terminated because "-W-error=cast-function-type" and "-W-error=class-memaccess".

export CFLAGS="$RPM_OPT_FLAGS -Wno-error=cast-function-type"
export CXXFLAGS="$RPM_OPT_FLAGS -std=gnu++98 -Wno-c++11-compat -Wno-error=cast-function-type -Wno-error=class-memaccess"

With those two env parameters, compiling works again. But it is just a workaround, please consider to fix those gcc/g++ syntax error.

thanks

**Comment by wuxb45** [comment]
+1

This is what I added to make it build:
```
  CXXFLAGS='-O3 -Wno-cast-function-type -Wno-maybe-uninitialized -Wno-format-truncation -Wno-class-memaccess'\
  CFLAGS='-O3 -Wno-cast-function-type -Wno-maybe-uninitialized -Wno-format-truncation'\
  LDFLAGS='-O3 -flto' ./configure --prefix=/usr \
              --enable-fw-mgr
```

**Comment by HonggangLI** [comment]
issue had been fixed. thanks
