### ISSUE TITLE
default generated configuration script ./configure.sh script fails, missing infiniband/mad.h

### ISSUE THREAD

**Issue by thuffmlx** [Mellanox/mstflint#207]
The .configure script generated by ./autogen.sh fails in t he default mode (build with inifiband).

checking infiniband/mad.h usability... no
checking infiniband/mad.h presence... no
checking for infiniband/mad.h... no
configure: error: cannot find infiniband/mad.h . Use --disable-inband to remove this dependaency

This will build successfully when the --disable-inband is used.

But default setup should build without errors.

**Comment by rob-scheepens** [comment]
Just hit this again with 4.14.0-3.

**Comment by thuffmlx** [comment]
Rob,

You’ll need to set compile flags.

FLAGS="--enable-adb-generic-tools --enable-openssl --disable-inband"

Tom

**Comment by tomer540** [comment]
Closed due to time limit, if still require addressing – please open a new ticket.
