### ISSUE TITLE
Questions about mstflint release versions 

### ISSUE THREAD

**Issue by bsnapko** [Mellanox/mstflint#21]
Questions about the 4.9 release numbering. 

At the URL : https://github.com/Mellanox/mstflint/releases
There are three 4.9.0 releases listed. They are 
4.9.0-3
4.9.0-2
4.9.0

The two versions named 4.9.0-3 and 4.9.0-2 download a file named mstflint-4.9.0-1.tar.gz. 
- Is this correct? 
- I would have expected each release to have to use the "-3" and "-2" as part of the file name to differentiate between the release versions. 

In the 4.9.0-3 version .tar.gz file. The file named mstflint.spec.in at the top level directory.
It has a line : 
%{!?release: %define release 2}

If the latest .tar.gz file is 4.9.0-3, then should the number value be 3 instead of 2? 

Thank you for your help.

**Comment by DanGoldbergMellanox** [comment]
Thank you for bringing this issue up.
I have updated our automation scripts and now the filename and the release version should match.

The next release will be with the updated versioning.
