### ISSUE TITLE
small_utils/mlxfwresetlib/mlxfwreset_status_checker.py format is different from other python scripts

### ISSUE THREAD

**Issue by HonggangLI** [Mellanox/mstflint#29]
mstflint-4.11.0 (master *)]$ find -name '*.py' | xargs file
./cmdif/cmdif.py:                                          Python script, ASCII text executable
./dev_mgt/dev_mgt.py:                                      Python script, ASCII text executable
./ext_libs/iniParser/test/twisted-genhuge.py:              Python script, ASCII text executable
./mlxconfig/mstprivhost.py:                                Python script, ASCII text executable
./mtcr_py/mtcr.py:                                         Python script, ASCII text executable
./mtcr_py/test.py:                                         Python script, ASCII text executable
./reg_access/regaccess.py:                                 Python script, ASCII text executable
./small_utils/mlxfwresetlib/mcra.py:                       Python script, ASCII text executable
./small_utils/mlxfwresetlib/mlnx_peripheral_components.py: Python script, ASCII text executable
./small_utils/mlxfwresetlib/mlxfwreset_mlnxdriver.py:      Python script, ASCII text executable

./small_utils/mlxfwresetlib/mlxfwreset_status_checker.py:  Python script, ASCII text executable, with CRLF, LF line terminators

./small_utils/mlxfwresetlib/mlxfwreset_utils.py:           Python script, ASCII text executable
./small_utils/mlxfwresetlib/pci_device.py:                 Python script, ASCII text executable
./small_utils/mlxfwresetlib/__init__.py:                   Python script, ASCII text executable
./small_utils/mlxfwresetlib/logger.py:                     Python script, ASCII text executable
./small_utils/mstfwreset.py:                               Python script, ASCII text executable

Please convert the format with 'dos2unix'.

**Comment by romanyano** [comment]
converted
