### ISSUE TITLE
python scripts with shebang but installed as not executables

### ISSUE THREAD

**Issue by HonggangLI** [Mellanox/mstflint#30]
mstflint (master)]$ find -name '*.py' | xargs grep -E '^#!/usr/bin'
./small_utils/mstfwreset.py:#!/usr/bin/python
./small_utils/mlxfwresetlib/mlxfwreset_utils.py:#!/usr/bin/python
./small_utils/mlxfwresetlib/mcra.py:#!/usr/bin/python
./small_utils/mlxfwresetlib/mlxfwreset_status_checker.py:#!/usr/bin/python
./small_utils/mlxfwresetlib/pci_device.py:#!/usr/bin/python
./small_utils/mlxfwresetlib/mlnx_peripheral_components.py:#!/usr/bin/python
./small_utils/mlxfwresetlib/mlxfwreset_mlnxdriver.py:#!/usr/bin/python
./mtcr_py/test.py:#!/usr/bin/env python

https://docs.fedoraproject.org/en-US/packaging-guidelines/#_shebang_lines

"Files which are not installed as executables SHOULD NOT have shebang lines."

mstflint installed all python scripts as not executables. If those files are not executables, we
should remove the shebang line for them. Or, we should install those files as executables.

**Comment by romanyano** [comment]
shebangs removed from non executable scripts.
