### ISSUE TITLE
need to replace 'mlxfwreset' with 'mstfwreset'

### ISSUE THREAD

**Issue by HonggangLI** [Mellanox/mstflint#32]
$ mstflint -d 05:00.0 -i ./fw-ConnectIB-rel-10_16_1200-MCB194A-FCA_A1.bin burn

    Current FW version on flash:  10.16.1020
    New FW version:               10.16.1200

Burning FW image without signatures - OK  
Restoring signature                     - OK
-I- To load new FW run mlxfwreset or reboot machine.
                                     ^^^^^^^^^^^

    ***** minor nitpick: above should state 'mstfwreset' instead of 'mlxfwreset' *****

$ rpm -qpl mstflint-4.11.0-2.el7.x86_64.rpm | grep fwreset | grep bin
/usr/bin/mstfwreset

There is no 'mlxfwreset' in the rpm. Only 'mstfwreset'.

**Comment by romanyano** [comment]
changed to mstfwreset
