### ISSUE TITLE
Please fix important covscan issues

### ISSUE THREAD

**Issue by HonggangLI** [Mellanox/mstflint#34]
Please note: there are false positive in the covscan report.

      9	BUFFER_SIZE_WARNING
      2	COPY_PASTE_ERROR

 mstflint-4.11.0-2.el8/scan-results-imp.err

Error: BUFFER_SIZE_WARNING (CWE-120):
mstflint-4.11.0/mlxfwops/lib/fs3_ops.cpp:237: buffer_size_warning: Calling strncpy with a maximum size argument of 97 bytes on destination array "this->_fs3ImgInfo.ext_info.orig_prs_name" of size 97 bytes might leave the destination string unterminated.
#  235|           memset(&tools_mfg_info, 0, sizeof(tools_mfg_info));
#  236|           tools_open_mfg_info_unpack(&tools_mfg_info, buff);
#  237|->         strncpy(_fs3ImgInfo.ext_info.orig_prs_name, tools_mfg_info.orig_prs_name, FS3_PRS_NAME_LEN);
#  238|       }
#  239|       return true;

Error: BUFFER_SIZE_WARNING (CWE-120):
mstflint-4.11.0/mlxfwops/lib/fs3_ops.cpp:314: buffer_size_warning: Calling strncpy with a maximum size argument of 65 bytes on destination array "this->_fs3ImgInfo.ext_info.name" of size 65 bytes might leave the destination string unterminated.
#  312|           memset(&tools_image_info, 0, sizeof(tools_image_info));
#  313|           tools_open_image_info_unpack(&tools_image_info, buff);
#  314|->         strncpy(_fs3ImgInfo.ext_info.name, tools_image_info.name, NAME_LEN);
#  315|           strncpy(_fs3ImgInfo.ext_info.description, tools_image_info.description, DESCRIPTION_LEN);
#  316|           strncpy(_fs3ImgInfo.ext_info.prs_name, tools_image_info.prs_name, FS3_PRS_NAME_LEN);

Error: BUFFER_SIZE_WARNING (CWE-120):
mstflint-4.11.0/mlxfwops/lib/fs3_ops.cpp:315: buffer_size_warning: Calling strncpy with a maximum size argument of 257 bytes on destination array "this->_fs3ImgInfo.ext_info.description" of size 257 bytes might leave the destination string unterminated.
#  313|           tools_open_image_info_unpack(&tools_image_info, buff);
#  314|           strncpy(_fs3ImgInfo.ext_info.name, tools_image_info.name, NAME_LEN);
#  315|->         strncpy(_fs3ImgInfo.ext_info.description, tools_image_info.description, DESCRIPTION_LEN);
#  316|           strncpy(_fs3ImgInfo.ext_info.prs_name, tools_image_info.prs_name, FS3_PRS_NAME_LEN);
#  317|       }

Error: BUFFER_SIZE_WARNING (CWE-120):
mstflint-4.11.0/mlxfwops/lib/fs3_ops.cpp:316: buffer_size_warning: Calling strncpy with a maximum size argument of 97 bytes on destination array "this->_fs3ImgInfo.ext_info.prs_name" of size 97 bytes might leave the destination string unterminated.
#  314|           strncpy(_fs3ImgInfo.ext_info.name, tools_image_info.name, NAME_LEN);
#  315|           strncpy(_fs3ImgInfo.ext_info.description, tools_image_info.description, DESCRIPTION_LEN);
#  316|->         strncpy(_fs3ImgInfo.ext_info.prs_name, tools_image_info.prs_name, FS3_PRS_NAME_LEN);
#  317|       }
#  318|       _fs3ImgInfo.ext_info.mcc_en = image_info.mcc_en;

Error: BUFFER_SIZE_WARNING (CWE-120):
mstflint-4.11.0/mlxfwops/lib/fs3_ops.cpp:1195: buffer_size_warning: Calling strncpy with a maximum size argument of 17 bytes on destination array "tools_image_info.psid" of size 17 bytes might leave the destination string unterminated.
# 1193|                   struct tools_open_image_info tools_image_info;
# 1194|                   tools_open_image_info_unpack(&tools_image_info, &imageInfoSect[0]);
# 1195|->                 strncpy(tools_image_info.psid, _fwImgInfo.ext_info.psid, PSID_LEN + 1);
# 1196|                   strncpy(tools_image_info.name, _fs3ImgInfo.ext_info.name, NAME_LEN);
# 1197|                   strncpy(tools_image_info.description, _fs3ImgInfo.ext_info.description, DESCRIPTION_LEN);

Error: BUFFER_SIZE_WARNING (CWE-120):
mstflint-4.11.0/mlxfwops/lib/fs3_ops.cpp:1196: buffer_size_warning: Calling strncpy with a maximum size argument of 65 bytes on destination array "tools_image_info.name" of size 65 bytes might leave the destination string unterminated.
# 1194|                   tools_open_image_info_unpack(&tools_image_info, &imageInfoSect[0]);
# 1195|                   strncpy(tools_image_info.psid, _fwImgInfo.ext_info.psid, PSID_LEN + 1);
# 1196|->                 strncpy(tools_image_info.name, _fs3ImgInfo.ext_info.name, NAME_LEN);
# 1197|                   strncpy(tools_image_info.description, _fs3ImgInfo.ext_info.description, DESCRIPTION_LEN);
# 1198|                   tools_open_image_info_pack(&tools_image_info, &imageInfoSect[0]);

Error: BUFFER_SIZE_WARNING (CWE-120):
mstflint-4.11.0/mlxfwops/lib/fs3_ops.cpp:1197: buffer_size_warning: Calling strncpy with a maximum size argument of 257 bytes on destination array "tools_image_info.description" of size 257 bytes might leave the destination string unterminated.
# 1195|                   strncpy(tools_image_info.psid, _fwImgInfo.ext_info.psid, PSID_LEN + 1);
# 1196|                   strncpy(tools_image_info.name, _fs3ImgInfo.ext_info.name, NAME_LEN);
# 1197|->                 strncpy(tools_image_info.description, _fs3ImgInfo.ext_info.description, DESCRIPTION_LEN);
# 1198|                   tools_open_image_info_pack(&tools_image_info, &imageInfoSect[0]);
# 1199|               }

Error: COPY_PASTE_ERROR (CWE-398):
mstflint-4.11.0/mlxfwops/lib/fs4_ops.cpp:1147: original: "flashObjWithOcr != NULL" looks like the original copy.
mstflint-4.11.0/mlxfwops/lib/fs4_ops.cpp:1067: copy_paste_error: "flashObjWithOcr" in "flashObjWithOcr != NULL" looks like a copy-paste error.
mstflint-4.11.0/mlxfwops/lib/fs4_ops.cpp:1067: remediation: Should it say "origFlashObj" instead?
# 1065|       }
# 1066|   
# 1067|->     if (flashObjWithOcr != NULL) {
# 1068|           _ioAccess = origFlashObj;
# 1069|           _fwParams.ignoreCacheRep = 0;

Error: BUFFER_SIZE_WARNING (CWE-120):
mstflint-4.11.0/mlxfwops/lib/fsctrl_ops.cpp:174: buffer_size_warning: Calling strncpy with a maximum size argument of 65 bytes on destination array "this->_fsCtrlImgInfo.name" of size 65 bytes might leave the destination string unterminated.
#  172|       }
#  173|   
#  174|->     strncpy(_fsCtrlImgInfo.name, fwQery.name, NAME_LEN);
#  175|       strncpy(_fsCtrlImgInfo.description, fwQery.description, DESCRIPTION_LEN);
#  176|   

Error: BUFFER_SIZE_WARNING (CWE-120):
mstflint-4.11.0/mlxfwops/lib/fsctrl_ops.cpp:175: buffer_size_warning: Calling strncpy with a maximum size argument of 257 bytes on destination array "this->_fsCtrlImgInfo.description" of size 257 bytes might leave the destination string unterminated.
#  173|   
#  174|       strncpy(_fsCtrlImgInfo.name, fwQery.name, NAME_LEN);
#  175|->     strncpy(_fsCtrlImgInfo.description, fwQery.description, DESCRIPTION_LEN);
#  176|   
#  177|       return true;

Error: COPY_PASTE_ERROR (CWE-398):
mstflint-4.11.0/mtcr_ul/mtcr_ul_icmd_cif.c:579: original: "mtcr_memaccess(mf, 0U, read_data_size, data, 0, MEM_ICMD)" looks like the original copy.
mstflint-4.11.0/mtcr_ul/mtcr_ul_icmd_cif.c:556: copy_paste_error: "read_data_size" in "mtcr_memaccess(mf, 0U, read_data_size, data, 1, MEM_ICMD)" looks like a copy-paste error.
mstflint-4.11.0/mtcr_ul/mtcr_ul_icmd_cif.c:556: remediation: Should it say "write_data_size" instead?
#  554|           DBG_PRINTF("-D- Writing command to mailbox");
#  555|           if (mf->icmd.dma_icmd) {
#  556|->             if (mtcr_memaccess(mf, 0, read_data_size, data, 1, MEM_ICMD)) {
#  557|                   ret = ME_ICMD_STATUS_CR_FAIL;
#  558|                   goto cleanup;

**Comment by tomer540** [comment]
Closed due to time limit, if still require addressing – please open a new ticket.
