### ISSUE TITLE
mstflint crash when compiled with 'CXXFLAGS='-Wp,-D_GLIBCXX_ASSERTIONS''

### ISSUE THREAD

**Issue by HonggangLI** [Mellanox/mstflint#36]
/opt/mstflint-assert-debug/bin/mstflint -y  -d 01:00.0 -i /root/fw-ConnectX4Lx-rel-14_24_1000-MCX4121A-ACA_Ax-UEFI-14.17.11-FlexBoot-3.5.603.bin burn

    Current FW version on flash:  14.24.1000
    New FW version:               14.24.1000

    Note: The new FW version is the same as the current FW version on flash.

 Do you want to continue ? (y/n) [n] : y

/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; std::vector<_Tp, _Alloc>::reference = unsigned char&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

This hack works for me.
```c
diff --git a/mlxfwops/lib/fs3_ops.cpp b/mlxfwops/lib/fs3_ops.cpp
index bfe8adb..8cf3f5e 100644
--- a/mlxfwops/lib/fs3_ops.cpp
+++ b/mlxfwops/lib/fs3_ops.cpp
@@ -525,7 +525,7 @@ bool Fs3Operations::VerifyTOC(u_int32_t dtoc_addr, bool &bad_signature, VerifyCa
                     }
                     // Only when we have full verify or the info of this section should be collected for query
                     std::vector<u_int8_t> buffv(entry_size_in_bytes);
-                    u_int8_t *buff = (u_int8_t *)(&(buffv[0]));
+                    u_int8_t *buff = (u_int8_t *)(buffv.size() ? (&(buffv[0])) : nullptr);
                     if (show_itoc) {
                         cibfw_itoc_entry_dump(&toc_entry, stdout);
                         if (!DumpFs3CRCCheck(toc_entry.type, phys_addr, entry_size_in_bytes, 0, 0, true, verifyCallBackFunc)) {

```

I also instrument the code to dump some message for debugging purpose.
mstflint (master *)]$ /opt/mstflint-print/bin/mstflint -d 01:00.0 -i /root/fw-ConnectX4Lx-rel-14_24_1000-MCX4121A-ACA_Ax-UEFI-14.17.11-FlexBoot-3.5.603.bin burn
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb8158, entry_size_in_bytes = 320
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb8158, entry_size_in_bytes = 650792
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb8158, entry_size_in_bytes = 1024
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb8158, entry_size_in_bytes = 512
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb8158, entry_size_in_bytes = 320
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb92b8, entry_size_in_bytes = 320
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb92b8, entry_size_in_bytes = 650792
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb92b8, entry_size_in_bytes = 1024
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb92b8, entry_size_in_bytes = 512
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb92b8, entry_size_in_bytes = 320
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb6748, entry_size_in_bytes = 320
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb6748, entry_size_in_bytes = 1024
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb6748, entry_size_in_bytes = 512
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb6748, entry_size_in_bytes = 320

    Current FW version on flash:  14.24.1000
    New FW version:               14.24.1000

    Note: The new FW version is the same as the current FW version on flash.

 Do you want to continue ? (y/n) [n] : y

fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66f8, entry_size_in_bytes = 320
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66f8, entry_size_in_bytes = 650792
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66f8, entry_size_in_bytes = 1024
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66f8, entry_size_in_bytes = 512
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66f8, entry_size_in_bytes = 320
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 256
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 3072
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 896
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 5504
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 320
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 11392
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 320
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 2304
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 144
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 576
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 4352
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 650792
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 65536
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 2560
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 39184
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 162308
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 55848
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 2891232
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 56608
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 3728
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 7460
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 1024
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 1944
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 8
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 65536
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 65536
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 65536
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 512
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 320
fs3_ops.cpp:VerifyTOC:528: buffv = 0xfffff5fb66e8, entry_size_in_bytes = 0
Initializing image partition -   OK
Writing Boot image component -   OK
-I- To load new FW run mlxfwreset or reboot machine.

**Comment by romanyano** [comment]
Fixed with the proposed hack except that instead of nullptr we used NULL (c++98 restrictions)
