### ISSUE TITLE
./configure.sh fails when openssl-devel is not installed

### ISSUE THREAD

**Issue by rob-scheepens** [Mellanox/mstflint#373]
Despite having openssl installed, ./configure failed with error:
```
...
checking for openssl/sha.h... no
configure: error: cannot find openssl/sha.h . remove --enable-openssl to remove this dependaency or install openssl
```
Installing openssl-devel as well fixed the error.

**Comment by ahmadawwad** [comment]
If you want to work with openssl features, you need to install openssl 
or u can run with --disable-openssl
