### ISSUE TITLE
kernel denied for mstconfig: lockdown_reason="direct PCI access"

### ISSUE THREAD

**Issue by thomas-weishaupl-rft** [Mellanox/mstflint#416]
It seams that mstflint has an issue with newer Linux Kernel versions (5.4+), which supports [kernel_lockdown](https://man7.org/linux/man-pages/man7/kernel_lockdown.7.html)

```
sh-4.4# mstconfig -v
mstconfig, mstflint 4.15.0, built on Nov 16 2020, 18:12:47. Git SHA Hash: N/A
sh-4.4# mstconfig -d af:00.0 q
write counter to semaphore: Permission denied
-E- Failed to open the device
sh-4.4# uname -a
Linux ... 5.13.4-200.fc34.x86_64 #1 SMP Tue Jul 20 20:27:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
sh-4.4# 
````

journal entry:
```
kernel: audit: type=1400 audit(1632295980.136:80874): avc:  denied  { integrity } for  pid=423824 comm="mstconfig" lockdown_reason="direct PCI access" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=lockdown permissive=0
```

I am not able to test latest mstfint version, but have only 4.15 available at the moment.

Anybody can confirm that latest mstfint has a fix, or it still an open issue? when will mstflint support kernel 5.4+ with kernel lockdown model enabled?

**Comment by ahmadawwad** [comment]
please work with latest mstflint , mstflint-4.18.0 , we`ve tested there with no issues
