### ISSUE TITLE
Flashed dual port firmware on single port card - can I fix it?

### ISSUE THREAD

**Issue by Jimmy-SafeCash** [Mellanox/mstflint#516]
Hello,

Rookie mistake, flashed a dual port firmware on a single port card. Can I reset and flash back to the original? Have tried flashing the right one, it works, but still shows as two ports...

I have a MCX353A-TCBT.

Thank you in advance.

**Comment by ahmadawwad** [comment]
not an issue and no reply from the one who opened

**Comment by Jimmy-SafeCash** [comment]
@ahmadawwad thanks for the response, only just seen this.

**Comment by Jimmy-SafeCash** [comment]
What's the best way to obtain the PSID and dev type?
