### ISSUE TITLE
issues reported by static checkers

### ISSUE THREAD

**Issue by michich** [Mellanox/mstflint#550]
Coverity scan found several new issues in mstflint 4.19 compared to 4.18. 
Attached is the output report. At least some of the findings look like real bugs. Please check.
[added.err.txt](https://github.com/Mellanox/mstflint/files/8372711/added.err.txt)

**Comment by tomer540** [comment]
thank you for the report, i have passed it to the relevant people.
I will update this thread once the issue is clarified.

**Comment by michich** [comment]
Here are issues reported by covscan static checkers (clang, coverity, cppcheck, gcc, shellcheck, unicontrol) static checkers in mstflint 4.21.0:
[scan-results.err.txt](https://github.com/Mellanox/mstflint/files/9257564/scan-results.err.txt)
