### ISSUE TITLE
mlxconfig - Invalid Phy Type error message has a mispelling

### ISSUE THREAD

**Issue by alandelgadoduran** [Mellanox/mstflint#599]
File: [mlxcfg_param_lib.cpp#L1459](https://github.com/Mellanox/mstflint/blob/fdd0577ac407637496b955d31d98cea86c62d00c/mlxconfig/mlxcfg_param_lib.cpp#L1459)

The word `shold` should be changed to `should`.  I checked the rest of the repo, this appears to be the only instance of the mispelling.

**Comment by ahmadawwad** [comment]
Hi, 
Thank you for updating us , we will handle in next release 
Thanks,
Ahmad Awwad

**Comment by tomer540** [comment]
fixed with release of 4.21
