### ISSUE TITLE
Dependency with pciutils

### ISSUE THREAD

**Issue by wizhaoredhat** [Mellanox/mstflint#785]
Without pciutils, we will get the following error message when running mstfwreset:

Continue with reset?[y/N] y
Failed
-E- failed to run 'setpci -s 0000:c9:02.0 0x0.w'.

The setpci command is part of the pciutils package.

@bn222 @SalDaniele

**Comment by bn222** [comment]
afair, pciutils should be part of the container. I've purposefully checked that. If not, it got removed which is something we need to catch from CI.

**Comment by SalDaniele** [comment]
We noticed the error due to failing CI jobs after the most recent firmware update. Installing pci utils in the config-daemon image results in mstfwreset running successfully https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/449

**Comment by wizhaoredhat** [comment]
@adrianchiris
