### ISSUE TITLE
How to read the temperature?

### ISSUE THREAD

**Issue by liubenyuan** [Mellanox/mstflint#831]
Hi, I installed mstflint under archlinux, and MCX623106A DX card is installed.
I found that there might be temperature related registers in mstflint, how could I read and print out the current chip temperature? just like the mget_temp command.

**Comment by ogalbxela** [comment]
Hi, mstflint doesn't provide alternative to the "mget_temp"-utility.

**Comment by liubenyuan** [comment]
Ok, thanks! I thought I could read and parse the registers and extract the board temperature.

**Comment by ogalbxela** [comment]
close as clarified

**Comment by ianb-mp** [comment]
`mget_temp` has been added to mstflint - see https://github.com/Mellanox/mstflint/pull/1029
