### ISSUE TITLE
mft ? mstflint  

### ISSUE THREAD

**Issue by xiaolongzhou123** [Mellanox/mstflint#999]
![img_v3_02et_43a1c350-9d7d-444b-9c75-dbc79a2eecfg](https://github.com/user-attachments/assets/70c2ad84-6b10-4a01-85d8-ac5a23c22baf)
"MFT? MSTFlint
Are the source codes of these two different?

Unable to read switch-related information remotely, such as mlxlink -d lid-xxx -p 1/1."

**Comment by xiaolongzhou123** [comment]
"MFT? MSTFlint
Are the source codes of these two different?

Unable to read switch-related information remotely, such as mlxlink -d lid-xxx -p 1/1."

**Comment by xiaolongzhou123** [comment]
"How can I download the source code for MFT?
I need to remotely read switch content through an API."

**Comment by ogalbxela** [comment]
mft and mstflint are not the same.

mft is proprietary product and only distributed in binary form https://network.nvidia.com/products/adapter-software/firmware-tools/
